FILES = \
    metacat \
    metacat_ui.py metacat_config.py  \
    metacat_auth.py metacat_dataset.py metacat_query.py metacat_file.py metacat_namespace.py \
	metacat_admin.py \
	query_test.py

build:	$(UI_DIR)
	cp $(FILES) $(UI_DIR)
	
$(UI_DIR):
	mkdir -p $@
